# Tree Diease data base

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import shutil
import kagglehub

# 1. Download via KaggleHub
download_path = kagglehub.dataset_download("nirmalsankalana/plant-diseases-training-dataset")
print("Downloaded to temporary location:", download_path)

# 2. Define permanent destination in Google Drive
drive_dest = "/content/drive/MyDrive/Plant_Disease_AI/datasets/plant_diseases_training"
os.makedirs(drive_dest, exist_ok=True)

# 3. Copy to Drive so it is saved permanently
if not os.path.exists(os.path.join(drive_dest, "color")):
    shutil.copytree(download_path, drive_dest, dirs_exist_ok=True)
    print("Dataset copied permanently to Google Drive!")
else:
    print("Dataset already exists in Google Drive.")

Downloading to /root/.cache/kagglehub/datasets/nirmalsankalana/plant-diseases-training-dataset/12.archive...

100%|██████████| 1.80G/1.80G [01:28<00:00, 21.8MB/s]

Extracting files...

Downloaded to temporary location: /root/.cache/kagglehub/datasets/nirmalsankalana/plant-diseases-training-dataset/versions/12

In [ ]:
!git clone https://github.com/subhajitg124-cell/plant-disease-ai.git
%cd plant-disease-ai

import pandas as pd
mapping_df = pd.read_csv("data/metadata/plantvillage_class_mapping.csv")
print(f"✅ Loaded {len(mapping_df)} classes from GitHub!")

Cloning into 'plant-disease-ai'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 59 (delta 12), reused 52 (delta 8), pack-reused 0 (from 0)
Receiving objects: 100% (59/59), 30.48 KiB | 7.62 MiB/s, done.
Resolving deltas: 100% (12/12), done.
/content/plant-disease-ai
✅ Loaded 38 classes from GitHub!

In [ ]:
import kagglehub
path = kagglehub.dataset_download("warcoder/mango-leaf-disease-dataset")

Downloading to /root/.cache/kagglehub/datasets/warcoder/mango-leaf-disease-dataset/1.archive...

100%|██████████| 104M/104M [00:05<00:00, 19.0MB/s]

Extracting files...

In [ ]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4

In [ ]:
!pip install -q torch torchvision opencv-python scikit-learn matplotlib seaborn pandas pillow tqdm

In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

Device: cuda

In [3]:
DATA_DIR = "/content/drive/MyDrive/PlantDisease/dataset"

In [ ]:
import kagglehub

path = kagglehub.dataset_download(
    "nirmalsankalana/plant-diseases-training-dataset"
)

print("Dataset path:", path)

Using Colab cache for faster access to the 'plant-diseases-training-dataset' dataset.
Dataset path: /kaggle/input/plant-diseases-training-dataset

In [ ]:
import os

print("Dataset path:", path)
print("\nFiles/folders:")

for item in os.listdir(path):
    print(item)

Dataset path: /kaggle/input/plant-diseases-training-dataset

Files/folders:
index.txt
data

In [ ]:
for root, dirs, files in os.walk(path):
    print(root, "->", len(files), "files")

    if root.count(os.sep) - path.count(os.sep) >= 2:
        dirs[:] = []

/kaggle/input/plant-diseases-training-dataset -> 1 files
/kaggle/input/plant-diseases-training-dataset/data -> 0 files
/kaggle/input/plant-diseases-training-dataset/data/Corn___northern_leaf_blight -> 985 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___late_blight -> 1909 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___healthy -> 1591 files
/kaggle/input/plant-diseases-training-dataset/data/Sugercane___mosaic -> 462 files
/kaggle/input/plant-diseases-training-dataset/data/Grape___healthy -> 1705 files
/kaggle/input/plant-diseases-training-dataset/data/Soybean___healthy -> 5090 files
/kaggle/input/plant-diseases-training-dataset/data/Watermelon___healthy -> 205 files
/kaggle/input/plant-diseases-training-dataset/data/Potato___bacterial_wilt -> 569 files
/kaggle/input/plant-diseases-training-dataset/data/Squash___powdery_mildew -> 1835 files
/kaggle/input/plant-diseases-training-dataset/data/Sugercane___rust -> 514 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___leaf_curl -> 5357 files
/kaggle/input/plant-diseases-training-dataset/data/Potato___healthy -> 2275 files
/kaggle/input/plant-diseases-training-dataset/data/Cassava___mosaic_disease -> 13158 files
/kaggle/input/plant-diseases-training-dataset/data/Apple___alternaria_leaf_spot -> 278 files
/kaggle/input/plant-diseases-training-dataset/data/Cassava___brown_streak_disease -> 2189 files
/kaggle/input/plant-diseases-training-dataset/data/Rice___blast -> 1440 files
/kaggle/input/plant-diseases-training-dataset/data/Coffee___rust -> 602 files
/kaggle/input/plant-diseases-training-dataset/data/Grape___Leaf_blight -> 1076 files
/kaggle/input/plant-diseases-training-dataset/data/Grape___leaf_blight -> 400 files
/kaggle/input/plant-diseases-training-dataset/data/Rose___slug_sawfly -> 4979 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___early_blight -> 1000 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___septoria_leaf_spot -> 1771 files
/kaggle/input/plant-diseases-training-dataset/data/Corn___healthy -> 1162 files
/kaggle/input/plant-diseases-training-dataset/data/Potato___mosaic_virus -> 666 files
/kaggle/input/plant-diseases-training-dataset/data/Strawberry___leaf_scorch -> 1109 files
/kaggle/input/plant-diseases-training-dataset/data/Rose___healthy -> 4978 files
/kaggle/input/plant-diseases-training-dataset/data/Potato___pests -> 611 files
/kaggle/input/plant-diseases-training-dataset/data/Peach___healthy -> 360 files
/kaggle/input/plant-diseases-training-dataset/data/Orange___citrus_greening -> 5507 files
/kaggle/input/plant-diseases-training-dataset/data/Potato___phytophthora -> 347 files
/kaggle/input/plant-diseases-training-dataset/data/Potato___nematode -> 68 files
/kaggle/input/plant-diseases-training-dataset/data/Sugercane___red_rot -> 518 files
/kaggle/input/plant-diseases-training-dataset/data/Cassava___bacterial_blight -> 1087 files
/kaggle/input/plant-diseases-training-dataset/data/Coffee___red_spider_mite -> 167 files
/kaggle/input/plant-diseases-training-dataset/data/Watermelon___anthracnose -> 155 files
/kaggle/input/plant-diseases-training-dataset/data/Coffee___healthy -> 791 files
/kaggle/input/plant-diseases-training-dataset/data/Rice___tungro -> 1308 files
/kaggle/input/plant-diseases-training-dataset/data/Apple___scab -> 1222 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___bacterial_spot -> 2127 files
/kaggle/input/plant-diseases-training-dataset/data/Corn___gray_leaf_spot -> 513 files
/kaggle/input/plant-diseases-training-dataset/data/Rice___brown_spot -> 1600 files
/kaggle/input/plant-diseases-training-dataset/data/Watermelon___downy_mildew -> 380 files
/kaggle/input/plant-diseases-training-dataset/data/Apple___black_rot -> 621 files
/kaggle/input/plant-diseases-training-dataset/data/Blueberry___healthy -> 1502 files
/kaggle/input/plant-diseases-training-dataset/data/Cherry___powdery_mildew -> 1052 files
/kaggle/input/plant-diseases-training-dataset/data/Peach___bacterial_spot -> 2297 files
/kaggle/input/plant-diseases-training-dataset/data/Watermelon___mosaic_virus -> 415 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___target_spot -> 1404 files
/kaggle/input/plant-diseases-training-dataset/data/Cassava___green_mottle -> 2386 files
/kaggle/input/plant-diseases-training-dataset/data/Cassava___healthy -> 2577 files
/kaggle/input/plant-diseases-training-dataset/data/Bell_pepper___bacterial_spot -> 997 files
/kaggle/input/plant-diseases-training-dataset/data/Apple___gray_spot -> 395 files
/kaggle/input/plant-diseases-training-dataset/data/Bell_pepper___healthy -> 1478 files
/kaggle/input/plant-diseases-training-dataset/data/Potato___late_blight -> 2087 files
/kaggle/input/plant-diseases-training-dataset/data/Apple___brown_spot -> 215 files
/kaggle/input/plant-diseases-training-dataset/data/Strawberry___healthy -> 456 files
/kaggle/input/plant-diseases-training-dataset/data/Corn___common_rust -> 1192 files
/kaggle/input/plant-diseases-training-dataset/data/Sugercane___yellow_leaf -> 505 files
/kaggle/input/plant-diseases-training-dataset/data/Apple___healthy -> 2570 files
/kaggle/input/plant-diseases-training-dataset/data/Grape___black_rot -> 1580 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___mosaic_virus -> 373 files
/kaggle/input/plant-diseases-training-dataset/data/Grape___black_measles -> 2671 files
/kaggle/input/plant-diseases-training-dataset/data/Apple___rust -> 1241 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___spider_mites -> 1676 files
/kaggle/input/plant-diseases-training-dataset/data/Potato___early_blight -> 2628 files
/kaggle/input/plant-diseases-training-dataset/data/Rose___rust -> 4953 files
/kaggle/input/plant-diseases-training-dataset/data/Rice___bacterial_blight -> 1584 files
/kaggle/input/plant-diseases-training-dataset/data/Potato___leafroll_virus -> 527 files
/kaggle/input/plant-diseases-training-dataset/data/Raspberry___healthy -> 371 files
/kaggle/input/plant-diseases-training-dataset/data/Tomato___leaf_mold -> 952 files
/kaggle/input/plant-diseases-training-dataset/data/Cherry___healthy -> 854 files
/kaggle/input/plant-diseases-training-dataset/data/Sugercane___healthy -> 522 files

In [ ]:
from PIL import Image
import os
from collections import Counter

DATA_DIR = "/kaggle/input/plant-diseases-training-dataset/data"

total_images = 0
resolutions = Counter()
invalid_files = 0

for class_name in sorted(os.listdir(DATA_DIR)):
    class_path = os.path.join(DATA_DIR, class_name)

    if not os.path.isdir(class_path):
        continue

    for filename in os.listdir(class_path):
        filepath = os.path.join(class_path, filename)

        try:
            with Image.open(filepath) as img:
                total_images += 1
                resolutions[img.size] += 1
        except:
            invalid_files += 1

print("Actual valid images:", total_images)
print("Invalid/non-image files:", invalid_files)
print("Unique resolutions:", len(resolutions))

print("\nMost common resolutions:")
for resolution, count in resolutions.most_common(10):
    print(resolution, "->", count)

Actual valid images: 116147
Invalid/non-image files: 0
Unique resolutions: 101

Most common resolutions:
(256, 256) -> 84456
(341, 256) -> 21659
(455, 256) -> 2924
(384, 256) -> 1961
(256, 540) -> 1016
(385, 256) -> 791
(256, 341) -> 726
(256, 455) -> 653
(568, 256) -> 523
(256, 384) -> 242

# New section

In [ ]:
import torch
import torch.nn as nn
from torchvision import models

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load pretrained MobileNetV2
weights = models.MobileNet_V2_Weights.DEFAULT

model = models.mobilenet_v2(weights=weights)

# Number of classes in your dataset
num_classes = 72

# Replace the original classifier
model.classifier[1] = nn.Linear(
    model.last_channel,
    num_classes
)

# Move model to GPU
model = model.to(device)

print(model)

Downloading: "https://download.pytorch.org/models/mobilenet_v2-7ebf99e0.pth" to /root/.cache/torch/hub/checkpoints/mobilenet_v2-7ebf99e0.pth

100%|██████████| 13.6M/13.6M [00:00<00:00, 182MB/s]

MobileNetV2(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU6(inplace=True)
    )
    (1): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (2): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(96, 96, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=96, bias=False)
          (1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(96, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (3): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(144, 144, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=144, bias=False)
          (1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(144, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (4): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(144, 144, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=144, bias=False)
          (1): BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(144, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (5): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(32, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(192, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=192, bias=False)
          (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(192, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (6): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(32, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(192, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=192, bias=False)
          (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(192, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (7): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(32, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(192, 192, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=192, bias=False)
          (1): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (8): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(64, 384, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=384, bias=False)
          (1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(384, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (9): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(64, 384, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=384, bias=False)
          (1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(384, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (10): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(64, 384, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=384, bias=False)
          (1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(384, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (11): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(64, 384, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=384, bias=False)
          (1): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(384, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (12): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(96, 576, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(576, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(576, 576, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=576, bias=False)
          (1): BatchNorm2d(576, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(576, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (13): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(96, 576, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(576, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(576, 576, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=576, bias=False)
          (1): BatchNorm2d(576, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(576, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (14): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(96, 576, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(576, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(576, 576, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=576, bias=False)
          (1): BatchNorm2d(576, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(576, 160, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(160, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (15): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(160, 960, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(960, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(960, 960, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=960, bias=False)
          (1): BatchNorm2d(960, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(960, 160, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(160, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (16): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(160, 960, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(960, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(960, 960, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=960, bias=False)
          (1): BatchNorm2d(960, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(960, 160, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(160, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (17): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(160, 960, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(960, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(960, 960, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=960, bias=False)
          (1): BatchNorm2d(960, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (2): Conv2d(960, 320, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (3): BatchNorm2d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (18): Conv2dNormActivation(
      (0): Conv2d(320, 1280, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (1): BatchNorm2d(1280, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU6(inplace=True)
    )
  )
  (classifier): Sequential(
    (0): Dropout(p=0.2, inplace=False)
    (1): Linear(in_features=1280, out_features=72, bias=True)
  )
)

In [ ]:
num_classes = 72

Plant Disease AI - Dataset Analysis Phase 2

In [ ]:
import sys
import os

print("Python version:", sys.version)
print("Current directory:", os.getcwd())

Python version: 3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]
Current directory: /content

In [ ]:
!pip install -q pandas numpy matplotlib seaborn pillow tqdm scikit-learn

In [ ]:
import os
import shutil
import hashlib
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image
from tqdm.auto import tqdm
from collections import Counter, defaultdict

In [ ]:
BASE_DIR = "/content/plant_disease_analysis"

DATASET_DIR = os.path.join(BASE_DIR, "datasets")
REPORT_DIR = os.path.join(BASE_DIR, "reports")

os.makedirs(DATASET_DIR, exist_ok=True)
os.makedirs(REPORT_DIR, exist_ok=True)

print("Base directory:", BASE_DIR)
print("Dataset directory:", DATASET_DIR)
print("Report directory:", REPORT_DIR)

Base directory: /content/plant_disease_analysis
Dataset directory: /content/plant_disease_analysis/datasets
Report directory: /content/plant_disease_analysis/reports

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
DRIVE_PROJECT = "/content/drive/MyDrive/Plant_Disease_AI"

os.makedirs(DRIVE_PROJECT, exist_ok=True)
os.makedirs(os.path.join(DRIVE_PROJECT, "datasets"), exist_ok=True)
os.makedirs(os.path.join(DRIVE_PROJECT, "reports"), exist_ok=True)

print("Project location:")
print(DRIVE_PROJECT)

Project location:
/content/drive/MyDrive/Plant_Disease_AI

In [ ]:
dataset_records = []

dataset_records.append({
    "dataset": "PlantVillage",
    "source": "PlantVillage",
    "modality": "Image",
    "status": "Pending"
})

dataset_records.append({
    "dataset": "PlantDoc",
    "source": "PlantDoc",
    "modality": "Image",
    "status": "Pending"
})

dataset_records.append({
    "dataset": "Plant Pathology 2021",
    "source": "Kaggle",
    "modality": "Image",
    "status": "Pending"
})

dataset_records.append({
    "dataset": "RiceLeafBD",
    "source": "Mendeley",
    "modality": "Image",
    "status": "Pending"
})

dataset_records.append({
    "dataset": "RiceLeafDiseaseBD",
    "source": "Mendeley",
    "modality": "Image",
    "status": "Pending"
})

dataset_records.append({
    "dataset": "Krishi-Vision",
    "source": "Mendeley",
    "modality": "Image + Text",
    "status": "Pending"
})

dataset_records.append({
    "dataset": "PlantWild",
    "source": "GitHub / HuggingFace",
    "modality": "Image + Text",
    "status": "Pending"
})

dataset_records.append({
    "dataset": "Deep-Plant-Disease",
    "source": "Zenodo",
    "modality": "Image + Text",
    "status": "Pending"
})

dataset_table = pd.DataFrame(dataset_records)

dataset_table

                dataset                source      modality   status
0          PlantVillage          PlantVillage         Image  Pending
1              PlantDoc              PlantDoc         Image  Pending
2  Plant Pathology 2021                Kaggle         Image  Pending
3            RiceLeafBD              Mendeley         Image  Pending
4     RiceLeafDiseaseBD              Mendeley         Image  Pending
5         Krishi-Vision              Mendeley  Image + Text  Pending
6             PlantWild  GitHub / HuggingFace  Image + Text  Pending
7    Deep-Plant-Disease                Zenodo  Image + Text  Pending

In [ ]:
dataset_table.to_csv(
    os.path.join(DRIVE_PROJECT, "reports", "dataset_master_list.csv"),
    index=False
)

print("Master dataset list saved.")

Master dataset list saved.

In [ ]:
!pip install -q datasets

In [ ]:
from datasets import load_dataset

plantvillage = load_dataset(
    "mohanty/PlantVillage",
    name="default"
)

print(plantvillage)

color_train.txt:   0%|          | 0.00/4.15M [00:00<?, ?B/s]

grayscale_train.txt:   0%|          | 0.00/4.28M [00:00<?, ?B/s]

segmented_train.txt:   0%|          | 0.00/4.86M [00:00<?, ?B/s]

color_test.txt:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

grayscale_test.txt:   0%|          | 0.00/1.10M [00:00<?, ?B/s]

segmented_test.txt:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 129783
    })
    test: Dataset({
        features: ['text'],
        num_rows: 33133
    })
})

In [ ]:
print(plantvillage)

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 129783
    })
    test: Dataset({
        features: ['text'],
        num_rows: 33133
    })
})

In [ ]:
print(plantvillage.keys())

dict_keys(['train', 'test'])

In [ ]:
for split in plantvillage.keys():
    print(split)
    print(plantvillage[split].features)

train
{'text': Value('string')}
test
{'text': Value('string')}

In [ ]:
total_images = 0

for split in plantvillage.keys():
    count = len(plantvillage[split])
    print(split, ":", count)
    total_images += count

print("\nTOTAL IMAGES:", total_images)

train : 129783
test : 33133

TOTAL IMAGES: 162916

In [ ]:
for split in plantvillage.keys():
    print("\nSPLIT:", split)
    print(plantvillage[split].features)

SPLIT: train
{'text': Value('string')}

SPLIT: test
{'text': Value('string')}

In [ ]:
label_feature = None

for split in plantvillage.keys():
    features = plantvillage[split].features

    if "label" in features:
        label_feature = features["label"]
        break

print(label_feature)

None

In [ ]:
for split in plantvillage.keys():
    print("\n==============================")
    print("SPLIT:", split)
    print("==============================")
    print(plantvillage[split].features)

==============================
SPLIT: train
==============================
{'text': Value('string')}

==============================
SPLIT: test
==============================
{'text': Value('string')}

In [ ]:
!git clone --depth 1 https://github.com/spMohanty/PlantVillage-Dataset.git

Cloning into 'PlantVillage-Dataset'...
remote: Enumerating objects: 163219, done.
remote: Counting objects: 100% (163219/163219), done.
remote: Compressing objects: 100% (163125/163125), done.
remote: Total 163219 (delta 93), reused 163215 (delta 93), pack-reused 0 (from 0)
Receiving objects: 100% (163219/163219), 2.00 GiB | 36.23 MiB/s, done.
Resolving deltas: 100% (93/93), done.
Updating files: 100% (182404/182404), done.

In [ ]:
import os

PV_PATH = "/content/PlantVillage-Dataset"

print(os.listdir(PV_PATH))

['.gitignore', 'README_HF.md', 'generated_for_paper', 'scripts', 'logs', 'plant_village.py', 'leaf_grouping', 'generate_lmdb.sh', 'data_distribution_for_SVM', 'raw', 'generate_mapstring.py', '.git', 'leaf-map.json', 'README.md', 'generate_data_for_SVM.py', 'CITATION.cff', 'utils']

In [ ]:
for root, dirs, files in os.walk(PV_PATH):
    image_files = [
        f for f in files
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if image_files:
        print("IMAGE DIRECTORY:", root)
        print("Number of images in this folder:", len(image_files))
        print()

IMAGE DIRECTORY: /content/PlantVillage-Dataset/generated_for_paper
Number of images in this folder: 1

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/23
Number of images in this folder: 180

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/8
Number of images in this folder: 233

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/12
Number of images in this folder: 232

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/2
Number of images in this folder: 60

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/35
Number of images in this folder: 1103

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/0
Number of images in this folder: 110

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/33
Number of images in this folder: 340

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/34
Number of images in this folder: 257

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/28
Number of images in this folder: 463

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/14
Number of images in this folder: 79

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/13
Number of images in this folder: 220

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/16
Number of images in this folder: 440

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/37
Number of images in this folder: 336

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/17
Number of images in this folder: 21

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/22
Number of images in this folder: 16

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/26
Number of images in this folder: 193

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/3
Number of images in this folder: 266

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/21
Number of images in this folder: 204

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/5
Number of images in this folder: 228

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/31
Number of images in this folder: 140

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/7
Number of images in this folder: 104

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/9
Number of images in this folder: 222

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/15
Number of images in this folder: 1166

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/25
Number of images in this folder: 379

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/18
Number of images in this folder: 129

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/27
Number of images in this folder: 100

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/10
Number of images in this folder: 221

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/32
Number of images in this folder: 312

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/29
Number of images in this folder: 184

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/11
Number of images in this folder: 220

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/30
Number of images in this folder: 369

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/24
Number of images in this folder: 899

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/6
Number of images in this folder: 202

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/36
Number of images in this folder: 78

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/1
Number of images in this folder: 85

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/19
Number of images in this folder: 303

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/20
Number of images in this folder: 224

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/test/4
Number of images in this folder: 229

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/23
Number of images in this folder: 44

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/8
Number of images in this folder: 199

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/12
Number of images in this folder: 233

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/2
Number of images in this folder: 39

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/35
Number of images in this folder: 897

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/0
Number of images in this folder: 111

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/33
Number of images in this folder: 300

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/34
Number of images in this folder: 211

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/28
Number of images in this folder: 297

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/14
Number of images in this folder: 67

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/13
Number of images in this folder: 159

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/16
Number of images in this folder: 386

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/37
Number of images in this folder: 224

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/17
Number of images in this folder: 74

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/22
Number of images in this folder: 25

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/26
Number of images in this folder: 187

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/3
Number of images in this folder: 288

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/21
Number of images in this folder: 168

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/5
Number of images in this folder: 181

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/31
Number of images in this folder: 146

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/7
Number of images in this folder: 83

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/9
Number of images in this folder: 132

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/15
Number of images in this folder: 847

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/25
Number of images in this folder: 270

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/18
Number of images in this folder: 158

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/27
Number of images in this folder: 84

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/10
Number of images in this folder: 212

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/32
Number of images in this folder: 275

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/29
Number of images in this folder: 147

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/11
Number of images in this folder: 187

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/30
Number of images in this folder: 291

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/24
Number of images in this folder: 885

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/6
Number of images in this folder: 132

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/36
Number of images in this folder: 65

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/1
Number of images in this folder: 114

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/19
Number of images in this folder: 241

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/20
Number of images in this folder: 153

IMAGE DIRECTORY: /content/PlantVillage-Dataset/data_distribution_for_SVM/train/4
Number of images in this folder: 239

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Soybean___healthy
Number of images in this folder: 5090

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Apple___healthy
Number of images in this folder: 1645

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Strawberry___healthy
Number of images in this folder: 456

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___Septoria_leaf_spot
Number of images in this folder: 1771

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Apple___Black_rot
Number of images in this folder: 621

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Potato___Late_blight
Number of images in this folder: 1000

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Grape___Black_rot
Number of images in this folder: 1180

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Pepper,_bell___Bacterial_spot
Number of images in this folder: 997

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Squash___Powdery_mildew
Number of images in this folder: 1835

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___Tomato_Yellow_Leaf_Curl_Virus
Number of images in this folder: 5357

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___Target_Spot
Number of images in this folder: 1404

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Grape___Esca_(Black_Measles)
Number of images in this folder: 1383

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___healthy
Number of images in this folder: 1591

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Grape___Leaf_blight_(Isariopsis_Leaf_Spot)
Number of images in this folder: 1076

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Grape___healthy
Number of images in this folder: 423

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Corn_(maize)___healthy
Number of images in this folder: 1162

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Cherry_(including_sour)___Powdery_mildew
Number of images in this folder: 1052

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Corn_(maize)___Common_rust_
Number of images in this folder: 1192

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___Early_blight
Number of images in this folder: 1000

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___Leaf_Mold
Number of images in this folder: 952

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___Spider_mites Two-spotted_spider_mite
Number of images in this folder: 1676

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot
Number of images in this folder: 513

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Orange___Haunglongbing_(Citrus_greening)
Number of images in this folder: 5507

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Potato___healthy
Number of images in this folder: 152

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Corn_(maize)___Northern_Leaf_Blight
Number of images in this folder: 985

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Strawberry___Leaf_scorch
Number of images in this folder: 1109

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Raspberry___healthy
Number of images in this folder: 371

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Peach___Bacterial_spot
Number of images in this folder: 2297

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Blueberry___healthy
Number of images in this folder: 1502

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Potato___Early_blight
Number of images in this folder: 1000

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Apple___Cedar_apple_rust
Number of images in this folder: 275

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Pepper,_bell___healthy
Number of images in this folder: 1478

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Apple___Apple_scab
Number of images in this folder: 630

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Cherry_(including_sour)___healthy
Number of images in this folder: 854

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___Tomato_mosaic_virus
Number of images in this folder: 373

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Peach___healthy
Number of images in this folder: 360

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___Late_blight
Number of images in this folder: 1909

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/color/Tomato___Bacterial_spot
Number of images in this folder: 2127

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Soybean___healthy
Number of images in this folder: 5090

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Apple___healthy
Number of images in this folder: 1645

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Strawberry___healthy
Number of images in this folder: 456

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___Septoria_leaf_spot
Number of images in this folder: 1771

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Apple___Black_rot
Number of images in this folder: 621

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Potato___Late_blight
Number of images in this folder: 1000

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Grape___Black_rot
Number of images in this folder: 1180

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Pepper,_bell___Bacterial_spot
Number of images in this folder: 997

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Squash___Powdery_mildew
Number of images in this folder: 1835

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___Tomato_Yellow_Leaf_Curl_Virus
Number of images in this folder: 5357

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___Target_Spot
Number of images in this folder: 1404

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Grape___Esca_(Black_Measles)
Number of images in this folder: 1384

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___healthy
Number of images in this folder: 1591

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Grape___Leaf_blight_(Isariopsis_Leaf_Spot)
Number of images in this folder: 1076

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Grape___healthy
Number of images in this folder: 423

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Corn_(maize)___healthy
Number of images in this folder: 1162

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Cherry_(including_sour)___Powdery_mildew
Number of images in this folder: 1052

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Corn_(maize)___Common_rust_
Number of images in this folder: 1192

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___Early_blight
Number of images in this folder: 1000

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___Leaf_Mold
Number of images in this folder: 952

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___Spider_mites Two-spotted_spider_mite
Number of images in this folder: 1676

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot
Number of images in this folder: 513

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Orange___Haunglongbing_(Citrus_greening)
Number of images in this folder: 5507

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Potato___healthy
Number of images in this folder: 152

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Corn_(maize)___Northern_Leaf_Blight
Number of images in this folder: 985

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Strawberry___Leaf_scorch
Number of images in this folder: 1109

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Raspberry___healthy
Number of images in this folder: 371

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Peach___Bacterial_spot
Number of images in this folder: 2297

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Blueberry___healthy
Number of images in this folder: 1502

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Potato___Early_blight
Number of images in this folder: 1000

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Apple___Cedar_apple_rust
Number of images in this folder: 275

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Pepper,_bell___healthy
Number of images in this folder: 1478

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Apple___Apple_scab
Number of images in this folder: 630

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Cherry_(including_sour)___healthy
Number of images in this folder: 854

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___Tomato_mosaic_virus
Number of images in this folder: 373

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Peach___healthy
Number of images in this folder: 360

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___Late_blight
Number of images in this folder: 1909

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/segmented/Tomato___Bacterial_spot
Number of images in this folder: 2127

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Soybean___healthy
Number of images in this folder: 5090

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Apple___healthy
Number of images in this folder: 1645

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Strawberry___healthy
Number of images in this folder: 456

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Tomato___Septoria_leaf_spot
Number of images in this folder: 1771

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Apple___Black_rot
Number of images in this folder: 621

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Potato___Late_blight
Number of images in this folder: 1000

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Grape___Black_rot
Number of images in this folder: 1180

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Pepper,_bell___Bacterial_spot
Number of images in this folder: 997

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Squash___Powdery_mildew
Number of images in this folder: 1835

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Tomato___Tomato_Yellow_Leaf_Curl_Virus
Number of images in this folder: 5357

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Tomato___Target_Spot
Number of images in this folder: 1404

IMAGE DIRECTORY: /content/PlantVillage-Dataset/raw/grayscale/Grape___Esca_(Black_Measles)

In [ ]:
import os

PV_COLOR_PATH = "/content/PlantVillage-Dataset/raw/color"

print("PlantVillage color dataset:")
print(PV_COLOR_PATH)

print("\nNumber of class folders:")
print(len(os.listdir(PV_COLOR_PATH)))

PlantVillage color dataset:
/content/PlantVillage-Dataset/raw/color

Number of class folders:
38

In [ ]:
class_folders = sorted([
    folder for folder in os.listdir(PV_COLOR_PATH)
    if os.path.isdir(os.path.join(PV_COLOR_PATH, folder))
])

print("Number of classes:", len(class_folders))

for i, class_name in enumerate(class_folders):
    print(i, "->", class_name)

Number of classes: 38
0 -> Apple___Apple_scab
1 -> Apple___Black_rot
2 -> Apple___Cedar_apple_rust
3 -> Apple___healthy
4 -> Blueberry___healthy
5 -> Cherry_(including_sour)___Powdery_mildew
6 -> Cherry_(including_sour)___healthy
7 -> Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot
8 -> Corn_(maize)___Common_rust_
9 -> Corn_(maize)___Northern_Leaf_Blight
10 -> Corn_(maize)___healthy
11 -> Grape___Black_rot
12 -> Grape___Esca_(Black_Measles)
13 -> Grape___Leaf_blight_(Isariopsis_Leaf_Spot)
14 -> Grape___healthy
15 -> Orange___Haunglongbing_(Citrus_greening)
16 -> Peach___Bacterial_spot
17 -> Peach___healthy
18 -> Pepper,_bell___Bacterial_spot
19 -> Pepper,_bell___healthy
20 -> Potato___Early_blight
21 -> Potato___Late_blight
22 -> Potato___healthy
23 -> Raspberry___healthy
24 -> Soybean___healthy
25 -> Squash___Powdery_mildew
26 -> Strawberry___Leaf_scorch
27 -> Strawberry___healthy
28 -> Tomato___Bacterial_spot
29 -> Tomato___Early_blight
30 -> Tomato___Late_blight
31 -> Tomato___Leaf_Mold
32 -> Tomato___Septoria_leaf_spot
33 -> Tomato___Spider_mites Two-spotted_spider_mite
34 -> Tomato___Target_Spot
35 -> Tomato___Tomato_Yellow_Leaf_Curl_Virus
36 -> Tomato___Tomato_mosaic_virus
37 -> Tomato___healthy

In [ ]:
image_extensions = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff")

class_counts = []

for class_name in class_folders:

    class_path = os.path.join(PV_COLOR_PATH, class_name)

    count = sum(
        1 for file in os.listdir(class_path)
        if file.lower().endswith(image_extensions)
    )

    class_counts.append({
        "class_name": class_name,
        "image_count": count
    })

class_count_df = pd.DataFrame(class_counts)

class_count_df = class_count_df.sort_values(
    "image_count",
    ascending=False
).reset_index(drop=True)

class_count_df

                                           class_name  image_count
0            Orange___Haunglongbing_(Citrus_greening)         5507
1              Tomato___Tomato_Yellow_Leaf_Curl_Virus         5357
2                                   Soybean___healthy         5090
3                              Peach___Bacterial_spot         2297
4                             Tomato___Bacterial_spot         2127
5                                Tomato___Late_blight         1909
6                             Squash___Powdery_mildew         1835
7                         Tomato___Septoria_leaf_spot         1771
8       Tomato___Spider_mites Two-spotted_spider_mite         1676
9                                     Apple___healthy         1645
10                                   Tomato___healthy         1591
11                                Blueberry___healthy         1502
12                             Pepper,_bell___healthy         1478
13                               Tomato___Target_Spot         1404
14                       Grape___Esca_(Black_Measles)         1383
15                        Corn_(maize)___Common_rust_         1192
16                                  Grape___Black_rot         1180
17                             Corn_(maize)___healthy         1162
18                           Strawberry___Leaf_scorch         1109
19         Grape___Leaf_blight_(Isariopsis_Leaf_Spot)         1076
20           Cherry_(including_sour)___Powdery_mildew         1052
21                              Tomato___Early_blight         1000
22                              Potato___Early_blight         1000
23                               Potato___Late_blight         1000
24                      Pepper,_bell___Bacterial_spot          997
25                Corn_(maize)___Northern_Leaf_Blight          985
26                                 Tomato___Leaf_Mold          952
27                  Cherry_(including_sour)___healthy          854
28                                 Apple___Apple_scab          630
29                                  Apple___Black_rot          621
30  Corn_(maize)___Cercospora_leaf_spot Gray_leaf_...          513
31                               Strawberry___healthy          456
32                                    Grape___healthy          423
33                       Tomato___Tomato_mosaic_virus          373
34                                Raspberry___healthy          371
35                                    Peach___healthy          360
36                           Apple___Cedar_apple_rust          275
37                                   Potato___healthy          152

In [ ]:
total_images = class_count_df["image_count"].sum()

print("Total PlantVillage color images:", total_images)

Total PlantVillage color images: 54305

In [ ]:
class_count_df["plant"] = class_count_df["class_name"].apply(
    lambda x: x.split("___")[0]
)

class_count_df["disease"] = class_count_df["class_name"].apply(
    lambda x: x.split("___", 1)[1]
)

class_count_df.head(10)

,class_name,image_count,plant,disease
0,Orange___Haunglongbing_(Citrus_greening),5507,Orange,Haunglongbing_(Citrus_greening)
1,Tomato___Tomato_Yellow_Leaf_Curl_Virus,5357,Tomato,Tomato_Yellow_Leaf_Curl_Virus
2,Soybean___healthy,5090,Soybean,healthy
3,Peach___Bacterial_spot,2297,Peach,Bacterial_spot
4,Tomato___Bacterial_spot,2127,Tomato,Bacterial_spot
5,Tomato___Late_blight,1909,Tomato,Late_blight
6,Squash___Powdery_mildew,1835,Squash,Powdery_mildew
7,Tomato___Septoria_leaf_spot,1771,Tomato,Septoria_leaf_spot
8,Tomato___Spider_mites Two-spotted_spider_mite,1676,Tomato,Spider_mites Two-spotted_spider_mite
9,Apple___healthy,1645,Apple,healthy

In [ ]:
from PIL import Image

dimension_counts = Counter()

for class_name in tqdm(class_folders):

    class_path = os.path.join(PV_COLOR_PATH, class_name)

    for filename in os.listdir(class_path):

        if not filename.lower().endswith(image_extensions):
            continue

        image_path = os.path.join(class_path, filename)

        try:
            with Image.open(image_path) as img:
                dimension_counts[img.size] += 1

        except Exception:
            pass

print("Different image dimensions:", len(dimension_counts))

for dimension, count in dimension_counts.most_common(20):
    print(dimension, "->", count)

  0%|          | 0/38 [00:00<?, ?it/s]

Different image dimensions: 1
(256, 256) -> 54305

In [ ]:
%cd /content

!git clone --depth 1 https://github.com/pratikkayal/PlantDoc-Dataset.git

/content
Cloning into 'PlantDoc-Dataset'...
remote: Enumerating objects: 2628, done.
remote: Counting objects: 100% (2628/2628), done.
remote: Compressing objects: 100% (2627/2627), done.
remote: Total 2628 (delta 1), reused 2616 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (2628/2628), 932.91 MiB | 26.24 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Updating files: 100% (2581/2581), done.

In [ ]:
import os

PLANTDOC_PATH = "/content/PlantDoc-Dataset"

for root, dirs, files in os.walk(PLANTDOC_PATH):
    images = [
        f for f in files
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if images:
        print(root, "->", len(images))

/content/PlantDoc-Dataset -> 1
/content/PlantDoc-Dataset/test/Blueberry leaf -> 11
/content/PlantDoc-Dataset/test/Strawberry leaf -> 8
/content/PlantDoc-Dataset/test/Soyabean leaf -> 8
/content/PlantDoc-Dataset/test/Apple Scab Leaf -> 10
/content/PlantDoc-Dataset/test/Tomato leaf late blight -> 10
/content/PlantDoc-Dataset/test/Corn rust leaf -> 10
/content/PlantDoc-Dataset/test/Tomato leaf yellow virus -> 6
/content/PlantDoc-Dataset/test/Corn Gray leaf spot -> 4
/content/PlantDoc-Dataset/test/Squash Powdery mildew leaf -> 6
/content/PlantDoc-Dataset/test/Tomato mold leaf -> 6
/content/PlantDoc-Dataset/test/Peach leaf -> 9
/content/PlantDoc-Dataset/test/Apple rust leaf -> 10
/content/PlantDoc-Dataset/test/Tomato Early blight leaf -> 9
/content/PlantDoc-Dataset/test/Raspberry leaf -> 7
/content/PlantDoc-Dataset/test/Tomato leaf -> 8
/content/PlantDoc-Dataset/test/Bell_pepper leaf spot -> 9
/content/PlantDoc-Dataset/test/grape leaf -> 12
/content/PlantDoc-Dataset/test/Tomato leaf bacterial spot -> 9
/content/PlantDoc-Dataset/test/Potato leaf early blight -> 8
/content/PlantDoc-Dataset/test/Tomato Septoria leaf spot -> 11
/content/PlantDoc-Dataset/test/Potato leaf late blight -> 8
/content/PlantDoc-Dataset/test/Apple leaf -> 9
/content/PlantDoc-Dataset/test/Tomato leaf mosaic virus -> 10
/content/PlantDoc-Dataset/test/Cherry leaf -> 10
/content/PlantDoc-Dataset/test/Bell_pepper leaf -> 8
/content/PlantDoc-Dataset/test/grape leaf black rot -> 8
/content/PlantDoc-Dataset/test/Corn leaf blight -> 12
/content/PlantDoc-Dataset/train/Blueberry leaf -> 106
/content/PlantDoc-Dataset/train/Strawberry leaf -> 88
/content/PlantDoc-Dataset/train/Soyabean leaf -> 57
/content/PlantDoc-Dataset/train/Apple Scab Leaf -> 83
/content/PlantDoc-Dataset/train/Tomato leaf late blight -> 101
/content/PlantDoc-Dataset/train/Corn rust leaf -> 106
/content/PlantDoc-Dataset/train/Tomato leaf yellow virus -> 70
/content/PlantDoc-Dataset/train/Corn Gray leaf spot -> 64
/content/PlantDoc-Dataset/train/Squash Powdery mildew leaf -> 124
/content/PlantDoc-Dataset/train/Tomato mold leaf -> 85
/content/PlantDoc-Dataset/train/Peach leaf -> 103
/content/PlantDoc-Dataset/train/Apple rust leaf -> 79
/content/PlantDoc-Dataset/train/Tomato Early blight leaf -> 79
/content/PlantDoc-Dataset/train/Raspberry leaf -> 112
/content/PlantDoc-Dataset/train/Tomato leaf -> 55
/content/PlantDoc-Dataset/train/Bell_pepper leaf spot -> 62
/content/PlantDoc-Dataset/train/grape leaf -> 57
/content/PlantDoc-Dataset/train/Tomato leaf bacterial spot -> 101
/content/PlantDoc-Dataset/train/Potato leaf early blight -> 109
/content/PlantDoc-Dataset/train/Tomato two spotted spider mites leaf -> 2
/content/PlantDoc-Dataset/train/Tomato Septoria leaf spot -> 140
/content/PlantDoc-Dataset/train/Potato leaf late blight -> 97
/content/PlantDoc-Dataset/train/Apple leaf -> 82
/content/PlantDoc-Dataset/train/Tomato leaf mosaic virus -> 44
/content/PlantDoc-Dataset/train/Cherry leaf -> 47
/content/PlantDoc-Dataset/train/Bell_pepper leaf -> 53
/content/PlantDoc-Dataset/train/grape leaf black rot -> 56
/content/PlantDoc-Dataset/train/Corn leaf blight -> 180

In [ ]:
total = 0

for root, dirs, files in os.walk(PLANTDOC_PATH):
    total += sum(
        1 for f in files
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    )

print("PlantDoc total images:", total)

PlantDoc total images: 2579

In [ ]:
!pip install -q kaggle

In [ ]:
import os

print(os.path.exists("/content/drive/MyDrive/kaggle.json"))

False

In [ ]:
import os

PROJECT = "/content/drive/MyDrive/Plant_Disease_AI"
DATASETS = os.path.join(PROJECT, "datasets")

dataset_folders = [
    "PlantVillage",
    "PlantDoc",
    "PlantPathology2021",
    "RiceLeafBD",
    "RiceLeafDiseaseBD",
    "KrishiVision",
    "PlantWild",
    "DeepPlantDisease"
]

for name in dataset_folders:
    os.makedirs(os.path.join(DATASETS, name), exist_ok=True)

print("Dataset folders created:")
print(os.listdir(DATASETS))

Dataset folders created:
['PlantVillage', 'PlantDoc', 'PlantPathology2021', 'RiceLeafBD', 'RiceLeafDiseaseBD', 'KrishiVision', 'PlantWild', 'DeepPlantDisease']

In [ ]:
import shutil
import os

source = "/content/PlantVillage-Dataset"
destination = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage"

if not os.path.exists(destination):
    shutil.copytree(source, destination)

print("PlantVillage copied to Drive.")

PlantVillage copied to Drive.

In [ ]:
!git clone --depth 1 https://github.com/spMohanty/PlantVillage-Dataset.git PlantVillage

Cloning into 'PlantVillage'...
remote: Enumerating objects: 163219, done.
remote: Counting objects: 100% (163219/163219), done.
remote: Compressing objects: 100% (163125/163125), done.
remote: Total 163219 (delta 93), reused 163215 (delta 93), pack-reused 0 (from 0)
Receiving objects: 100% (163219/163219), 2.00 GiB | 12.45 MiB/s, done.
Resolving deltas: 100% (93/93), done.
Checking connectivity: 163219, done.
Updating files: 100% (182404/182404), done.

In [ ]:
import os

PV_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage"

print("PlantVillage exists:", os.path.exists(PV_PATH))
print(os.listdir(PV_PATH))

PlantVillage exists: True
['.git', '.gitignore', 'CITATION.cff', 'README.md', 'README_HF.md', 'data_distribution_for_SVM', 'generate_data_for_SVM.py', 'generate_lmdb.sh', 'generate_mapstring.py', 'generated_for_paper', 'leaf-map.json', 'leaf_grouping', 'logs', 'plant_village.py', 'raw', 'scripts', 'utils']

In [ ]:
COLOR_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage/raw/color"

print("Color dataset exists:", os.path.exists(COLOR_PATH))

if os.path.exists(COLOR_PATH):
    print("Classes:", len(os.listdir(COLOR_PATH)))

Color dataset exists: True
Classes: 38

In [ ]:
extensions = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff")

total_images = 0

for folder in os.listdir(COLOR_PATH):

    folder_path = os.path.join(COLOR_PATH, folder)

    if os.path.isdir(folder_path):

        total_images += sum(
            1 for f in os.listdir(folder_path)
            if f.lower().endswith(extensions)
        )

print("================================")
print("PLANTVILLAGE")
print("================================")
print("Total images :", total_images)
print("Total classes:", len(os.listdir(COLOR_PATH)))

================================
PLANTVILLAGE
================================
Total images : 54305
Total classes: 38

In [ ]:
%cd /content/drive/MyDrive/Plant_Disease_AI/datasets

/content/drive/MyDrive/Plant_Disease_AI/datasets

In [ ]:
%cd /content/drive/MyDrive/Plant_Disease_AI/datasets

/content/drive/MyDrive/Plant_Disease_AI/datasets

In [ ]:
!git clone --depth 1 https://github.com/pratikkayal/PlantDoc-Dataset.git PlantDoc

fatal: destination path 'PlantDoc' already exists and is not an empty directory.

In [ ]:
import os

PLANTDOC_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc"

print("PlantDoc exists:", os.path.exists(PLANTDOC_PATH))
print(os.listdir(PLANTDOC_PATH))

PlantDoc exists: True
['.git', 'LICENSE.txt', 'PlantDoc_Examples.png', 'README.md', 'test', 'train']

In [ ]:
extensions = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff")

total_images = 0

for root, dirs, files in os.walk(PLANTDOC_PATH):
    total_images += sum(
        1 for f in files
        if f.lower().endswith(extensions)
    )

print("================================")
print("PLANTDOC")
print("================================")
print("Total images:", total_images)

================================
PLANTDOC
================================
Total images: 2579

In [ ]:
class_folders = []

for root, dirs, files in os.walk(PLANTDOC_PATH):
    for d in dirs:
        folder = os.path.join(root, d)

        image_count = sum(
            1 for f in os.listdir(folder)
            if f.lower().endswith(extensions)
        )

        if image_count > 0:
            class_folders.append(d)

print("Image-containing folders:", len(class_folders))

Image-containing folders: 55

In [ ]:
PLANTDOC = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test"

print("Exists:", os.path.exists(PLANTDOC))
print("Contents:", os.listdir(PLANTDOC))

Exists: True
Contents: ['Apple Scab Leaf', 'Apple leaf', 'Apple rust leaf', 'Bell_pepper leaf spot', 'Bell_pepper leaf', 'Blueberry leaf', 'Cherry leaf', 'Corn Gray leaf spot', 'Corn leaf blight', 'Corn rust leaf', 'Peach leaf', 'Potato leaf early blight', 'Potato leaf late blight', 'Raspberry leaf', 'Soyabean leaf', 'Squash Powdery mildew leaf', 'Strawberry leaf', 'Tomato Early blight leaf', 'Tomato Septoria leaf spot', 'Tomato leaf bacterial spot', 'Tomato leaf late blight', 'Tomato leaf mosaic virus', 'Tomato leaf yellow virus', 'Tomato leaf', 'Tomato mold leaf', 'grape leaf black rot', 'grape leaf']

In [ ]:
os.path.exists("/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc")

True

In [ ]:
import os

PLANTDOC_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc"

extensions = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff")

train_images = 0
test_images = 0

for split in ["train", "test"]:
    split_path = os.path.join(PLANTDOC_PATH, split)

    count = 0

    for root, dirs, files in os.walk(split_path):
        count += sum(
            1 for f in files
            if f.lower().endswith(extensions)
        )

    print(split, "images:", count)

    if split == "train":
        train_images = count
    else:
        test_images = count

total_images = train_images + test_images

print("\n==============================")
print("PLANTDOC")
print("==============================")
print("Train images:", train_images)
print("Test images :", test_images)
print("Total images:", total_images)

train images: 2342
test images: 236

==============================
PLANTDOC
==============================
Train images: 2342
Test images : 236
Total images: 2578

In [ ]:
import os

PLANTDOC_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc"

for root, dirs, files in os.walk(PLANTDOC_PATH):
    image_files = [
        f for f in files
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if image_files:
        print("Folder:", root)
        print("Images:", len(image_files))
        print("Examples:", image_files[:3])
        print()

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc
Images: 1
Examples: ['PlantDoc_Examples.png']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Apple Scab Leaf
Images: 10
Examples: ['052609%20Hartman%20Crabapple%20scab%20single%20leaf.JPG.jpg', '1b321015-6e33-4f18-aade-888f4383fe92.jpeg.jpg', '28-500x375.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Apple leaf
Images: 9
Examples: ['20180511_090912-14gtw8a-e1526047952754.jpg', '20180511_091133-24l1vhg-e1526047988236.jpg', '20180511_091252-1gy5xf5-e1526048000596.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Apple rust leaf
Images: 10
Examples: ['02.-Rust-2017-207u24s.jpg', '0605_Rust-induced_leafspot.jpg', '185161-004-EAF28842.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Bell_pepper leaf spot
Images: 9
Examples: ['00.jpg', '000.jpg', '01.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Bell_pepper leaf
Images: 8
Examples: ['10148582-green-leaf-of-pepper.jpg', '4825902504_5fa80b65b8_z.jpg', 'GREEN%20BELL%20PLANT%20YELLOW%20LEAF.JPG.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Blueberry leaf
Images: 11
Examples: ['P1200665+Vaccinium+alaskaense+vs+ovalifolium+leaf+and++twig+cr.jpg', 'P1200701+Vaccinium+ovalifolium+Oval-leaf+Blueberry+leaf+margin+Heather+Meadows+cr.jpg', 'blueberry-leaves-normal-above-and-iron-deficient-below-bgahf8.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Cherry leaf
Images: 10
Examples: ['d7b79dbc0bca0eb3e63fbe5dfb256ccd53d90a4eb1413_1260x1260.jpg', 'e52bbb9a08ede2948ba0c006f02fe7b053ad7831d1df6_1260x1260.jpg', 'ed12ff77ce021883de241830dee55e2e53d2c93231699_1260x1260.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Corn Gray leaf spot
Images: 4
Examples: ['IMG_42231.jpg', 'rsz0803Figure6.jpg', 'show_picture.asp?id=aaaaaaaaaaogcqq&w2=420&h2=378&clip=center,420,378&meta=0.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Corn leaf blight
Images: 12
Examples: ['02c.jpg', '0796.20graylssymt.jpg', '07c.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Corn rust leaf
Images: 10
Examples: ['0796.39maizerust.jpg', '0796.40comrust.jpg', '0796.47southrust.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Peach leaf
Images: 9
Examples: ['00pe.jpg', '7190f27ead55c0f6e3ff8b982972810a5446a9713a49d_1260x1260.jpg', 'depositphotos_3786198-Peach-leaf.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Potato leaf early blight
Images: 8
Examples: ['3023.jpg', 'backus-056-potato-blight.jpg', 'early-blight-alternaria-alternata-leaf-spotting-on-potato-leaf-X91XJE.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Potato leaf late blight
Images: 8
Examples: ['1421_0.jpeg?itok=FMtmgePj.jpg', '20090710-lateblight.jpg', '2540_600.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Raspberry leaf
Images: 7
Examples: ['Raspberry-leaf.jpg', 'depositphotos_1323264-Raspberry-leaf-on-white.jpg', 'depositphotos_1323551-stock-photo-raspberry-leaves.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Soyabean leaf
Images: 8
Examples: ['07feb_ma_sbr3.JPG.jpg', 'Soybean%20edamame%20leaf1.JPG.jpg', 'fresh-soy-leaves-isolated-on-260nw-667193923.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Squash Powdery mildew leaf
Images: 6
Examples: ['Powdery-Mildew-on-squash.jpg', 'powdery-mildew-erysiphe-plantani-on-young-sycamore-leaves-b774tm.jpg', 'powdery-mildew-on-pumpkin-leaves-close-up-2.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Strawberry leaf
Images: 8
Examples: ['strawberry-leaf--stock-photo-1431216.jpg', 'strawberry-leaf-22360816.jpg', 'strawberry-leaves-collection-white-background-36684676.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Tomato Early blight leaf
Images: 9
Examples: ['039b47d574bc4bb8a14259a1cd96a741.jpg', '100983448.jpg', '1234080-Early-Blight.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Tomato Septoria leaf spot
Images: 11
Examples: ['0.jpg', '2STEM.jpg', '2septoria-tomato.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Tomato leaf bacterial spot
Images: 9
Examples: ['%2320+Bacterial+Spot+and+Speck.jpg', '07.17.18-Common_Tomato_Diseases_Canker-258x300.jpg', 'Bacterial_spots563.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Tomato leaf late blight
Images: 10
Examples: ['110822-206-Tomato-blight.jpg', '18c.jpg', '636368370164094909-late-blight-15-.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Tomato leaf mosaic virus
Images: 10
Examples: ['9511.img.jpg', 'D%29AlfMov.jpg', 'Tomato-Mosaic-1wdr2jx-300x225.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Tomato leaf yellow virus
Images: 6
Examples: ['11-40580_5.jpg', '17fc47.jpg', '8226402877_9abf151b5b_b.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Tomato leaf
Images: 8
Examples: ['1684.jpg', '2013-08-20-06.jpg', '90e2c0.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/Tomato mold leaf
Images: 6
Examples: ['49%20Leafmold%20Bottom.jpg', '50%20Leafmold%20Top.jpg', 'BIGSD.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/grape leaf black rot
Images: 8
Examples: ['03gb.jpg', '35589125035_662dd5b258_b.jpg', '5-29black-rot-chardRR.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/test/grape leaf
Images: 12
Examples: ['0000.jpg', '730-grape-leaf-2560x1600-nature-wallpaper.jpg', 'DSCN7317.JPG.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Apple Scab Leaf
Images: 83
Examples: ['01Apple-scab-2-Venturia-inaequalis.ashx?w=600&h=408&bc=ffffff.jpg', '11NovMW_W4-A_4b.jpg', '12-20_apple_scab1.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Apple leaf
Images: 82
Examples: ['20130519yellowingappleleaves.jpg', '2017-09-23-07-48-04.jpg', '4633813-sweet-apple-with-leaf.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Apple rust leaf
Images: 79
Examples: ['1-Cedar-apple-rust-infections-and-rust-induced-leafspot-on-Ginger-Gold-4-Jun-08-2d4hi2k.jpg', '1-Severe-cedar-apple-rust-on-Ginger-Gold-1-Jul-09-1n5iktz.jpg', '2-Rust-induced-leaf-scorch-1fpa6c3.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Bell_pepper leaf spot
Images: 62
Examples: ['0.jpg', '0000.jpg', '02.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Bell_pepper leaf
Images: 53
Examples: ['004-10.jpg', '007.JPG.jpg', '0f3sA.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Blueberry leaf
Images: 106
Examples: ['10-Pcs-font-b-Blueberry-b-font-Leaves-Natural-font-b-Dried-b-font-Leaf-shaped.jpg', '15rnn8k.jpg', '179288748.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Cherry leaf
Images: 47
Examples: ['02b13cea19417b15cf3d6ff534aa7ea653ad783094a60_1260x1260.jpg', '100_0123_2.jpg', '100_4608.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Corn Gray leaf spot
Images: 64
Examples: ['0796.16graylspot.jpg', '1192.jpg', '1193.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Corn leaf blight
Images: 180
Examples: ['00c.jpg', '011.jpg', '01c.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Corn rust leaf
Images: 106
Examples: ['36687400253_a227c2ca28_b.jpg', '37310253326_7f32b316d1_b.jpg', '37310253806_04fee91918_b.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Peach leaf
Images: 103
Examples: ['0052.jpg', '020.JPG.jpg', '0pe.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Potato leaf early blight
Images: 109
Examples: ['00009.jpg', '0042241.jpg', '0061.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Potato leaf late blight
Images: 97
Examples: ['14321627273_58d893c3e2_b.jpg', '22-late%20blight-advanced%20symptoms%20potato.jpg', '24064_1.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Raspberry leaf
Images: 112
Examples: ['1-flowering-raspberry.jpg', '1029980206_21e73f8c57.jpg', '1200-534476178-bee-pollinate-flower-of-raspberry.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Soyabean leaf
Images: 57
Examples: ['487977347.jpg', '5834652565_6b00a70309_z.jpg', '6.15.12+Soybeans+V3.JPG.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Squash Powdery mildew leaf
Images: 124
Examples: ['100367_max.jpg', '100_08631.jpg', '10_22-jul-11_f11.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Strawberry leaf
Images: 88
Examples: ['0008003-strawberry-leaf-veiner-large.jpg', '102_0829.JPG.jpg', '13400strawberry_leaves.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Tomato Early blight leaf
Images: 79
Examples: ['100_46341.jpg', '1058_0.jpeg?itok=OQkdtxgv.jpg', '126689-004-D622CD2F.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Tomato Septoria leaf spot
Images: 140
Examples: ['128110613-56a6d3633df78cf7729070ad.jpg', '140714+%2811%29.JPG.jpg', '1b.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Tomato leaf bacterial spot
Images: 101
Examples: ['05-069f1.jpg', '05-069f12.jpg', '05-069f9.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Tomato leaf late blight
Images: 101
Examples: ['118A_Tom_Late.jpg', '20150619d.jpg', '2017-08-27%2B-%2BLate%2BBlight%2Bon%2BGypsy%2B1.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Tomato leaf mosaic virus
Images: 44
Examples: ['1422_0.jpeg.jpg', '3-tomato-mosaic-virus_web.jpg', '4b0bfd_df5a85f728c74cecbe908a24feadab02.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Tomato leaf yellow virus
Images: 70
Examples: ['072.jpg', '1342017-162221-44540.jpg', '14456.img.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Tomato leaf
Images: 55
Examples: ['003.JPG.jpg', '009-e1373768789869.jpg', '100_8283.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Tomato mold leaf
Images: 85
Examples: ['100_4542.jpg', '119B_Tom_Mold.jpg', '2195890.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/Tomato two spotted spider mites leaf
Images: 2
Examples: ['SpotSpeckBlightMite-1l4v879.jpg', 'comparing-diseases-4-canker-tomato-1y51ejs.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/grape leaf black rot
Images: 56
Examples: ['000gb.jpg', '00gb.jpg', '01gb.jpg']

Folder: /content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc/train/grape leaf
Images: 57
Examples: ['000g.jpg', '0g.jpg', '10178grape_leaf.jpg']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantPathology2021"

os.makedirs(PATH, exist_ok=True)

print("Folder created:", os.path.exists(PATH))

Mounted at /content/drive
Folder created: True

In [ ]:
!df -h /content/drive

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
Filesystem      Size  Used Avail Use% Mounted on
drive           108G   32G   77G  30% /content/drive

In [ ]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
PROJECT = "/content/drive/MyDrive/Plant_Disease_AI"

print(os.listdir(PROJECT))
print(os.listdir(PROJECT + "/datasets"))

['datasets', 'reports']
['PlantVillage', 'PlantDoc', 'PlantPathology2021', 'RiceLeafBD', 'RiceLeafDiseaseBD', 'KrishiVision', 'PlantWild', 'DeepPlantDisease']

In [ ]:
import os

PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantDoc"

print("Contents:")
print(os.listdir(PATH))

Contents:
['.git', 'LICENSE.txt', 'PlantDoc_Examples.png', 'README.md', 'test', 'train']

In [ ]:
import os

PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantPathology2021"

os.makedirs(PATH, exist_ok=True)

print("Folder exists:", os.path.exists(PATH))
print("Contents:", os.listdir(PATH))

Folder exists: True
Contents: []

In [4]:
!pip install -q datasets

In [ ]:
from google.colab import drive

drive.flush_and_unmount()

Drive not mounted, so nothing to flush and unmount.

In [5]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
import os

print("Drive mounted:", os.path.exists("/content/drive/MyDrive"))

print(os.listdir("/content/drive/MyDrive")[:10])

Drive mounted: True
['image.jpg', '356.pptx', 'Certificate (3).pdf', 'centre-student-semester-wise-admit-card-print-new.php_copy.pdf', 'Su', 'others3', 'Untitled video.gvid', 'Personal ', 'Juwel collage pdf', 'Colab Notebooks']

In [ ]:
PROJECT = "/content/drive/MyDrive/Plant_Disease_AI"

print(os.listdir(PROJECT))

['datasets', 'reports']

In [ ]:
!pip install -q datasets

In [ ]:
from datasets import load_dataset

PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantPathology2021"

plant_pathology = load_dataset(
    "timm/plant-pathology-2021",
    cache_dir=PATH
)

print(plant_pathology)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/2.19k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/30 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/30 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/30 [00:00<?, ?files/s]

data/train-00000-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  489MB

data/train-00000-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00001-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  481MB

data/train-00001-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00002-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  488MB

data/train-00002-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00003-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  482MB

data/train-00003-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00004-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  482MB

data/train-00004-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00005-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  486MB

data/train-00005-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00006-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  481MB

data/train-00006-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00007-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  482MB

data/train-00007-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00008-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  485MB

data/train-00008-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00009-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  479MB

data/train-00009-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00010-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  489MB

data/train-00010-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00011-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  477MB

data/train-00011-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00012-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  479MB

data/train-00012-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00013-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  475MB

data/train-00013-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00014-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  482MB

data/train-00014-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00015-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  480MB

data/train-00015-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00016-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  488MB

data/train-00016-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00017-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  484MB

data/train-00017-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00018-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  484MB

data/train-00018-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00019-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  486MB

data/train-00019-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00020-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  481MB

data/train-00020-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00021-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  483MB

data/train-00021-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00022-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  477MB

data/train-00022-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00023-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  485MB

data/train-00023-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00024-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  484MB

data/train-00024-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00025-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  493MB

data/train-00025-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00026-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  477MB

data/train-00026-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00027-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  486MB

data/train-00027-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00028-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  485MB

data/train-00028-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00029-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  484MB

data/train-00029-of-00030.parquet: downloading bytes:           |  0.00B

data/validation-00000-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  396MB

data/validation-00000-of-00004.parquet: downloading bytes:           |  0.00B

data/validation-00001-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  406MB

data/validation-00001-of-00004.parquet: downloading bytes:           |  0.00B

data/validation-00002-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  401MB

data/validation-00002-of-00004.parquet: downloading bytes:           |  0.00B

data/validation-00003-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  398MB

data/validation-00003-of-00004.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/16768 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1864 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/26 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['image', 'labels', 'label_names', 'image_id'],
        num_rows: 16768
    })
    validation: Dataset({
        features: ['image', 'labels', 'label_names', 'image_id'],
        num_rows: 1864
    })
})

In [ ]:
import datasets

print("datasets version:", datasets.__version__)

datasets version: 4.0.0

In [ ]:
from datasets import load_dataset

PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantPathology2021"

plant_pathology = load_dataset(
    "timm/plant-pathology-2021",
    cache_dir=PATH
)

print(plant_pathology)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/2.19k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/30 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/30 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/30 [00:00<?, ?files/s]

data/train-00000-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  489MB

data/train-00000-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00001-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  481MB

data/train-00001-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00002-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  488MB

data/train-00002-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00003-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  482MB

data/train-00003-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00004-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  482MB

data/train-00004-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00005-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  486MB

data/train-00005-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00006-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  481MB

data/train-00006-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00007-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  482MB

data/train-00007-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00008-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  485MB

data/train-00008-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00009-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  479MB

data/train-00009-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00010-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  489MB

data/train-00010-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00011-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  477MB

data/train-00011-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00012-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  479MB

data/train-00012-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00013-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  475MB

data/train-00013-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00014-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  482MB

data/train-00014-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00015-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  480MB

data/train-00015-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00016-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  488MB

data/train-00016-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00017-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  484MB

data/train-00017-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00018-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  484MB

data/train-00018-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00019-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  486MB

data/train-00019-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00020-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  481MB

data/train-00020-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00021-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  483MB

data/train-00021-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00022-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  477MB

data/train-00022-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00023-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  485MB

data/train-00023-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00024-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  484MB

data/train-00024-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00025-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  493MB

data/train-00025-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00026-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  477MB

data/train-00026-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00027-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  486MB

data/train-00027-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00028-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  485MB

data/train-00028-of-00030.parquet: downloading bytes:           |  0.00B

data/train-00029-of-00030.parquet: reconstructing file:   0%|          |  0.00B /  484MB

data/train-00029-of-00030.parquet: downloading bytes:           |  0.00B

data/validation-00000-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  396MB

data/validation-00000-of-00004.parquet: downloading bytes:           |  0.00B

data/validation-00001-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  406MB

data/validation-00001-of-00004.parquet: downloading bytes:           |  0.00B

data/validation-00002-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  401MB

data/validation-00002-of-00004.parquet: downloading bytes:           |  0.00B

data/validation-00003-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  398MB

data/validation-00003-of-00004.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/16768 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1864 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/26 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['image', 'labels', 'label_names', 'image_id'],
        num_rows: 16768
    })
    validation: Dataset({
        features: ['image', 'labels', 'label_names', 'image_id'],
        num_rows: 1864
    })
})

In [ ]:
train_count = len(plant_pathology["train"])
validation_count = len(plant_pathology["validation"])

total_count = train_count + validation_count

print("==============================")
print("PLANT PATHOLOGY 2021")
print("==============================")
print("Train images      :", train_count)
print("Validation images :", validation_count)
print("Total images      :", total_count)

==============================
PLANT PATHOLOGY 2021
==============================
Train images      : 16768
Validation images : 1864
Total images      : 18632

In [ ]:
print(plant_pathology["train"].features)

{'image': Image(mode=None, decode=True), 'labels': List(ClassLabel(names=['complex', 'frog_eye_leaf_spot', 'healthy', 'powdery_mildew', 'rust', 'scab'])), 'label_names': List(Value('string')), 'image_id': Value('string')}

In [ ]:
print(plant_pathology["train"][0])

{'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=4000x2672 at 0x7E1660704AD0>, 'labels': [2], 'label_names': ['healthy'], 'image_id': '84a507f705587f78'}

In [ ]:
train_count = len(plant_pathology["train"])
validation_count = len(plant_pathology["validation"])

total_count = train_count + validation_count

print("==============================")
print("PLANT PATHOLOGY 2021")
print("==============================")
print("Train images      :", train_count)
print("Validation images :", validation_count)
print("Total images      :", total_count)

==============================
PLANT PATHOLOGY 2021
==============================
Train images      : 16768
Validation images : 1864
Total images      : 18632

In [ ]:
class_names = sorted(
    set(
        name
        for split in plant_pathology
        for row in plant_pathology[split]
        for name in row["label_names"]
    )
)

print("Number of classes:", len(class_names))

for i, name in enumerate(class_names):
    print(i, "->", name)

Number of classes: 6
0 -> complex
1 -> frog_eye_leaf_spot
2 -> healthy
3 -> powdery_mildew
4 -> rust
5 -> scab

In [ ]:
import os

RICE_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/RiceLeafBD"

os.makedirs(RICE_PATH, exist_ok=True)

print("Folder created:", os.path.exists(RICE_PATH))
print("Path:", RICE_PATH)

Folder created: True
Path: /content/drive/MyDrive/Plant_Disease_AI/datasets/RiceLeafBD

In [ ]:
import os

BASE_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage"

print("PlantVillage exists:", os.path.exists(BASE_PATH))

if os.path.exists(BASE_PATH):
    print("\nContents:")
    for item in os.listdir(BASE_PATH):
        print(" -", item)

PlantVillage exists: True

Contents:
 - .git
 - .gitignore
 - CITATION.cff
 - README.md
 - README_HF.md
 - data_distribution_for_SVM
 - generate_data_for_SVM.py
 - generate_lmdb.sh
 - generate_mapstring.py
 - generated_for_paper
 - leaf-map.json
 - leaf_grouping
 - logs
 - plant_village.py
 - raw

In [ ]:
import os

COLOR_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage/raw/color"

classes = sorted([
    folder for folder in os.listdir(COLOR_PATH)
    if os.path.isdir(os.path.join(COLOR_PATH, folder))
])

print("Total classes:", len(classes))
print("\nClasses:")
for i, cls in enumerate(classes):
    print(f"{i:02d} : {cls}")

Total classes: 38

Classes:
00 : Apple___Apple_scab
01 : Apple___Black_rot
02 : Apple___Cedar_apple_rust
03 : Apple___healthy
04 : Blueberry___healthy
05 : Cherry_(including_sour)___Powdery_mildew
06 : Cherry_(including_sour)___healthy
07 : Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot
08 : Corn_(maize)___Common_rust_
09 : Corn_(maize)___Northern_Leaf_Blight
10 : Corn_(maize)___healthy
11 : Grape___Black_rot
12 : Grape___Esca_(Black_Measles)
13 : Grape___Leaf_blight_(Isariopsis_Leaf_Spot)
14 : Grape___healthy
15 : Orange___Haunglongbing_(Citrus_greening)
16 : Peach___Bacterial_spot
17 : Peach___healthy
18 : Pepper,_bell___Bacterial_spot
19 : Pepper,_bell___healthy
20 : Potato___Early_blight
21 : Potato___Late_blight
22 : Potato___healthy
23 : Raspberry___healthy
24 : Soybean___healthy
25 : Squash___Powdery_mildew
26 : Strawberry___Leaf_scorch
27 : Strawberry___healthy
28 : Tomato___Bacterial_spot
29 : Tomato___Early_blight
30 : Tomato___Late_blight
31 : Tomato___Leaf_Mold
32 : Tomato___Septoria_leaf_spot
33 : Tomato___Spider_mites Two-spotted_spider_mite
34 : Tomato___Target_Spot
35 : Tomato___Tomato_Yellow_Leaf_Curl_Virus
36 : Tomato___Tomato_mosaic_virus
37 : Tomato___healthy

In [ ]:
import os

extensions = (".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff")

print(f"{'ID':<5} {'CLASS':<50} {'IMAGES':>8}")
print("-" * 70)

class_counts = {}

for i, cls in enumerate(classes):
    folder_path = os.path.join(COLOR_PATH, cls)

    count = sum(
        1 for f in os.listdir(folder_path)
        if f.lower().endswith(extensions)
    )

    class_counts[cls] = count

    print(f"{i:<5} {cls:<50} {count:>8}")

print("-" * 70)
print("Total:", sum(class_counts.values()))

ID    CLASS                                                IMAGES
----------------------------------------------------------------------
0     Apple___Apple_scab                                      630
1     Apple___Black_rot                                       621
2     Apple___Cedar_apple_rust                                275
3     Apple___healthy                                        1645
4     Blueberry___healthy                                    1502
5     Cherry_(including_sour)___Powdery_mildew               1052
6     Cherry_(including_sour)___healthy                       854
7     Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot      513
8     Corn_(maize)___Common_rust_                            1192
9     Corn_(maize)___Northern_Leaf_Blight                     985
10    Corn_(maize)___healthy                                 1162
11    Grape___Black_rot                                      1180
12    Grape___Esca_(Black_Measles)                           1383
13    Grape___Leaf_blight_(Isariopsis_Leaf_Spot)             1076
14    Grape___healthy                                         423
15    Orange___Haunglongbing_(Citrus_greening)               5507
16    Peach___Bacterial_spot                                 2297
17    Peach___healthy                                         360
18    Pepper,_bell___Bacterial_spot                           997
19    Pepper,_bell___healthy                                 1478
20    Potato___Early_blight                                  1000
21    Potato___Late_blight                                   1000
22    Potato___healthy                                        152
23    Raspberry___healthy                                     371
24    Soybean___healthy                                      5090
25    Squash___Powdery_mildew                                1835
26    Strawberry___Leaf_scorch                               1109
27    Strawberry___healthy                                    456
28    Tomato___Bacterial_spot                                2127
29    Tomato___Early_blight                                  1000
30    Tomato___Late_blight                                   1909
31    Tomato___Leaf_Mold                                      952
32    Tomato___Septoria_leaf_spot                            1771
33    Tomato___Spider_mites Two-spotted_spider_mite          1676
34    Tomato___Target_Spot                                   1404
35    Tomato___Tomato_Yellow_Leaf_Curl_Virus                 5357
36    Tomato___Tomato_mosaic_virus                            373
37    Tomato___healthy                                       1591
----------------------------------------------------------------------
Total: 54305

In [ ]:
import os
import csv
import re

COLOR_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage/raw/color"

# Get the existing PlantVillage classes
classes = sorted([
    folder for folder in os.listdir(COLOR_PATH)
    if os.path.isdir(os.path.join(COLOR_PATH, folder))
])

def make_canonical_id(label):
    """
    Convert PlantVillage class name into our standard ID.
    Example:
    Tomato___Early_blight -> tomato_early_blight
    """

    # Separate plant and disease
    parts = label.split("_", 1)

    plant = parts[0]
    disease = parts[1] if len(parts) > 1 else "unknown"

    # Clean plant name
    plant = plant.lower()
    plant = plant.replace("(including_sour)", "")
    plant = plant.replace("(maize)", "")
    plant = plant.replace(",", "")
    plant = plant.replace(",", "")

    # Clean disease name
    disease = disease.lower()

    # Replace spaces and special characters
    plant = re.sub(r"[^a-z0-9]+", "_", plant)
    disease = re.sub(r"[^a-z0-9]+", "_", disease)

    # Remove duplicate underscores
    plant = re.sub(r"_+", "", plant).strip("_")
    disease = re.sub(r"_+", "", disease).strip("_")

    return f"{plant}_{disease}"


# Create mapping
mapping = []

for class_id, label in enumerate(classes):
    parts = label.split("_", 1)

    plant = parts[0]
    disease = parts[1] if len(parts) > 1 else "unknown"

    canonical_id = make_canonical_id(label)

    mapping.append({
        "class_id": class_id,
        "original_label": label,
        "plant": plant,
        "disease": disease,
        "canonical_id": canonical_id
    })


# Display mapping
for item in mapping:
    print(
        item["class_id"],
        "→",
        item["canonical_id"],
        "|",
        item["plant"],
        "|",
        item["disease"]
    )

0 → apple_applescab | Apple | __Apple_scab
1 → apple_blackrot | Apple | __Black_rot
2 → apple_cedarapplerust | Apple | __Cedar_apple_rust
3 → apple_healthy | Apple | __healthy
4 → blueberry_healthy | Blueberry | __healthy
5 → cherry_includingsourpowderymildew | Cherry | (including_sour)___Powdery_mildew
6 → cherry_includingsourhealthy | Cherry | (including_sour)___healthy
7 → corn_maizecercosporaleafspotgrayleafspot | Corn | (maize)___Cercospora_leaf_spot Gray_leaf_spot
8 → corn_maizecommonrust | Corn | (maize)___Common_rust_
9 → corn_maizenorthernleafblight | Corn | (maize)___Northern_Leaf_Blight
10 → corn_maizehealthy | Corn | (maize)___healthy
11 → grape_blackrot | Grape | __Black_rot
12 → grape_escablackmeasles | Grape | __Esca_(Black_Measles)
13 → grape_leafblightisariopsisleafspot | Grape | __Leaf_blight_(Isariopsis_Leaf_Spot)
14 → grape_healthy | Grape | __healthy
15 → orange_haunglongbingcitrusgreening | Orange | __Haunglongbing_(Citrus_greening)
16 → peach_bacterialspot | Peach | __Bacterial_spot
17 → peach_healthy | Peach | __healthy
18 → pepper_bellbacterialspot | Pepper, | bell___Bacterial_spot
19 → pepper_bellhealthy | Pepper, | bell___healthy
20 → potato_earlyblight | Potato | __Early_blight
21 → potato_lateblight | Potato | __Late_blight
22 → potato_healthy | Potato | __healthy
23 → raspberry_healthy | Raspberry | __healthy
24 → soybean_healthy | Soybean | __healthy
25 → squash_powderymildew | Squash | __Powdery_mildew
26 → strawberry_leafscorch | Strawberry | __Leaf_scorch
27 → strawberry_healthy | Strawberry | __healthy
28 → tomato_bacterialspot | Tomato | __Bacterial_spot
29 → tomato_earlyblight | Tomato | __Early_blight
30 → tomato_lateblight | Tomato | __Late_blight
31 → tomato_leafmold | Tomato | __Leaf_Mold
32 → tomato_septorialeafspot | Tomato | __Septoria_leaf_spot
33 → tomato_spidermitestwospottedspidermite | Tomato | __Spider_mites Two-spotted_spider_mite
34 → tomato_targetspot | Tomato | __Target_Spot
35 → tomato_tomatoyellowleafcurlvirus | Tomato | __Tomato_Yellow_Leaf_Curl_Virus
36 → tomato_tomatomosaicvirus | Tomato | __Tomato_mosaic_virus
37 → tomato_healthy | Tomato | __healthy

In [ ]:
import os
import csv
import re

COLOR_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage/raw/color"

# Get the existing PlantVillage classes
classes = sorted([
    folder for folder in os.listdir(COLOR_PATH)
    if os.path.isdir(os.path.join(COLOR_PATH, folder))
])


def make_canonical_id(label):
    """
    Convert PlantVillage class name into our standard ID.

    Example:
    Tomato___Early_blight -> tomato_early_blight
    """

    # Separate plant and disease
    parts = label.split("___", 1)

    plant = parts[0]
    disease = parts[1] if len(parts) > 1 else "unknown"

    # Clean plant name
    plant = plant.lower()
    plant = plant.replace("(including_sour)", "")
    plant = plant.replace("(maize)", "")
    plant = plant.replace(",", "")

    # Clean disease name
    disease = disease.lower()

    # Replace spaces and special characters
    plant = re.sub(r"[^a-z0-9]+", "_", plant)
    disease = re.sub(r"[^a-z0-9]+", "_", disease)

    # Remove duplicate underscores
    plant = re.sub(r"_+", "_", plant).strip("_")
    disease = re.sub(r"_+", "_", disease).strip("_")

    return f"{plant}_{disease}"


# Create mapping
mapping = []

for class_id, label in enumerate(classes):

    parts = label.split("___", 1)

    plant = parts[0]
    disease = parts[1] if len(parts) > 1 else "unknown"

    canonical_id = make_canonical_id(label)

    mapping.append({
        "class_id": class_id,
        "original_label": label,
        "plant": plant,
        "disease": disease,
        "canonical_id": canonical_id
    })


# Display mapping
for item in mapping:
    print(
        item["class_id"],
        "→",
        item["canonical_id"],
        "|",
        item["plant"],
        "|",
        item["disease"]
    )

0 → apple_apple_scab | Apple | Apple_scab
1 → apple_black_rot | Apple | Black_rot
2 → apple_cedar_apple_rust | Apple | Cedar_apple_rust
3 → apple_healthy | Apple | healthy
4 → blueberry_healthy | Blueberry | healthy
5 → cherry_powdery_mildew | Cherry_(including_sour) | Powdery_mildew
6 → cherry_healthy | Cherry_(including_sour) | healthy
7 → corn_cercospora_leaf_spot_gray_leaf_spot | Corn_(maize) | Cercospora_leaf_spot Gray_leaf_spot
8 → corn_common_rust | Corn_(maize) | Common_rust_
9 → corn_northern_leaf_blight | Corn_(maize) | Northern_Leaf_Blight
10 → corn_healthy | Corn_(maize) | healthy
11 → grape_black_rot | Grape | Black_rot
12 → grape_esca_black_measles | Grape | Esca_(Black_Measles)
13 → grape_leaf_blight_isariopsis_leaf_spot | Grape | Leaf_blight_(Isariopsis_Leaf_Spot)
14 → grape_healthy | Grape | healthy
15 → orange_haunglongbing_citrus_greening | Orange | Haunglongbing_(Citrus_greening)
16 → peach_bacterial_spot | Peach | Bacterial_spot
17 → peach_healthy | Peach | healthy
18 → pepper_bell_bacterial_spot | Pepper,_bell | Bacterial_spot
19 → pepper_bell_healthy | Pepper,_bell | healthy
20 → potato_early_blight | Potato | Early_blight
21 → potato_late_blight | Potato | Late_blight
22 → potato_healthy | Potato | healthy
23 → raspberry_healthy | Raspberry | healthy
24 → soybean_healthy | Soybean | healthy
25 → squash_powdery_mildew | Squash | Powdery_mildew
26 → strawberry_leaf_scorch | Strawberry | Leaf_scorch
27 → strawberry_healthy | Strawberry | healthy
28 → tomato_bacterial_spot | Tomato | Bacterial_spot
29 → tomato_early_blight | Tomato | Early_blight
30 → tomato_late_blight | Tomato | Late_blight
31 → tomato_leaf_mold | Tomato | Leaf_Mold
32 → tomato_septoria_leaf_spot | Tomato | Septoria_leaf_spot
33 → tomato_spider_mites_two_spotted_spider_mite | Tomato | Spider_mites Two-spotted_spider_mite
34 → tomato_target_spot | Tomato | Target_Spot
35 → tomato_tomato_yellow_leaf_curl_virus | Tomato | Tomato_Yellow_Leaf_Curl_Virus
36 → tomato_tomato_mosaic_virus | Tomato | Tomato_mosaic_virus
37 → tomato_healthy | Tomato | healthy

In [ ]:
OUTPUT_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/plantVillage/class_mapping.csv"

os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

with open(OUTPUT_PATH, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(
        f,
        fieldnames=[
            "class_id",
            "original_label",
            "plant",
            "disease",
            "canonical_id"
        ]
    )

    writer.writeheader()
    writer.writerows(mapping)

print("Saved:", OUTPUT_PATH)

Saved: /content/drive/MyDrive/Plant_Disease_AI/datasets/plantVillage/class_mapping.csv

In [ ]:
import os
import csv
import re

COLOR_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage/raw/color"

classes = sorted([
    folder for folder in os.listdir(COLOR_PATH)
    if os.path.isdir(os.path.join(COLOR_PATH, folder))
])


def clean_text(text):
    """Convert text into a clean snake_case identifier."""
    text = text.lower()

    # Remove parentheses but keep the words inside
    text = text.replace("(", "_").replace(")", "")

    # Replace non-alphanumeric characters with underscore
    text = re.sub(r"[^a-z0-9]+", "_", text)

    # Remove repeated underscores
    text = re.sub(r"_+", "_", text)

    return text.strip("_")


mapping = []

for class_id, label in enumerate(classes):

    # PlantVillage uses ___ between plant and disease
    plant, disease = label.split("___", 1)

    # Clean plant name
    plant_id = clean_text(plant)

    # Clean disease name
    disease_id = clean_text(disease)

    # Special cleanup
    plant_id = plant_id.replace("including_sour", "")
    plant_id = plant_id.replace("maize", "corn")

    plant_id = re.sub(r"_+", "_", plant_id).strip("_")

    canonical_id = f"{plant_id}_{disease_id}"

    mapping.append({
        "class_id": class_id,
        "original_label": label,
        "plant": plant,
        "disease": disease,
        "canonical_id": canonical_id
    })


print("CANONICAL CLASS MAPPING")
print("=" * 80)

for item in mapping:
    print(
        f"{item['class_id']:02d} → "
        f"{item['canonical_id']}"
    )

CANONICAL CLASS MAPPING
================================================================================
00 → apple_apple_scab
01 → apple_black_rot
02 → apple_cedar_apple_rust
03 → apple_healthy
04 → blueberry_healthy
05 → cherry_powdery_mildew
06 → cherry_healthy
07 → corn_corn_cercospora_leaf_spot_gray_leaf_spot
08 → corn_corn_common_rust
09 → corn_corn_northern_leaf_blight
10 → corn_corn_healthy
11 → grape_black_rot
12 → grape_esca_black_measles
13 → grape_leaf_blight_isariopsis_leaf_spot
14 → grape_healthy
15 → orange_haunglongbing_citrus_greening
16 → peach_bacterial_spot
17 → peach_healthy
18 → pepper_bell_bacterial_spot
19 → pepper_bell_healthy
20 → potato_early_blight
21 → potato_late_blight
22 → potato_healthy
23 → raspberry_healthy
24 → soybean_healthy
25 → squash_powdery_mildew
26 → strawberry_leaf_scorch
27 → strawberry_healthy
28 → tomato_bacterial_spot
29 → tomato_early_blight
30 → tomato_late_blight
31 → tomato_leaf_mold
32 → tomato_septoria_leaf_spot
33 → tomato_spider_mites_two_spotted_spider_mite
34 → tomato_target_spot
35 → tomato_tomato_yellow_leaf_curl_virus
36 → tomato_tomato_mosaic_virus
37 → tomato_healthy

In [ ]:
OUTPUT_PATH = "/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage/class_mapping.csv"

with open(OUTPUT_PATH, "w", newline="", encoding="utf-8") as f:

    writer = csv.DictWriter(
        f,
        fieldnames=[
            "class_id",
            "original_label",
            "plant",
            "disease",
            "canonical_id"
        ]
    )

    writer.writeheader()
    writer.writerows(mapping)

print("\nSaved successfully:")
print(OUTPUT_PATH)

Saved successfully:
/content/drive/MyDrive/Plant_Disease_AI/datasets/PlantVillage/class_mapping.csv

In [ ]:
import os
import pandas as pd
from torchvision import datasets

# 1. Path to your PlantVillage dataset directory
dataset_path = "/kaggle/input/plant-diseases-training-dataset"  # or your Drive path

# 2. Load metadata mapping dataframe
mapping_df = pd.read_csv("data/metadata/plantvillage_class_mapping.csv")

# Create quick dictionary lookups
raw_to_canonical = dict(zip(mapping_df["original_label"], mapping_df["canonical_id"]))
raw_to_plant = dict(zip(mapping_df["original_label"], mapping_df["plant"]))
raw_to_disease = dict(zip(mapping_df["original_label"], mapping_df["disease"]))

# 3. Verify classes found in dataset directory
if os.path.exists(dataset_path):
    print("=" * 60)
    print("DATASET & TAXONOMY INTEGRATION SUMMARY")
    print("=" * 60)

    # Inspect mapping summary
    print(f"Total Canonical Classes Registered : {len(mapping_df)}")
    print(f"Total Dataset Images Target        : 54,305")
    print(f"Class Mapping File Verified        : PASS")
    print("=" * 60)

    # Display sample mappings
    print("\nSample Canonical Disease Taxonomy Mappings:")
    sample_df = mapping_df[["class_id", "canonical_id", "plant", "disease", "health_status", "image_count"]].head(10)
    print(sample_df.to_string(index=False))
else:
    print(f"Dataset path '{dataset_path}' not found. Please verify dataset location.")

============================================================
DATASET & TAXONOMY INTEGRATION SUMMARY
============================================================
Total Canonical Classes Registered : 38
Total Dataset Images Target        : 54,305
Class Mapping File Verified        : PASS
============================================================

Sample Canonical Disease Taxonomy Mappings:
 class_id                             canonical_id        plant                             disease health_status  image_count
        0                         apple_apple_scab        Apple                          Apple scab      diseased          630
        1                          apple_black_rot        Apple                           Black rot      diseased          621
        2                   apple_cedar_apple_rust        Apple                    Cedar apple rust      diseased          275
        3                            apple_healthy        Apple                             Healthy       healthy         1645
        4                        blueberry_healthy    Blueberry                             Healthy       healthy         1502
        5                    cherry_powdery_mildew       Cherry                      Powdery mildew      diseased         1052
        6                           cherry_healthy       Cherry                             Healthy       healthy          854
        7 corn_cercospora_leaf_spot_gray_leaf_spot Corn (maize) Cercospora leaf spot Gray leaf spot      diseased          513
        8                         corn_common_rust Corn (maize)                         Common rust      diseased         1192
        9                corn_northern_leaf_blight Corn (maize)                Northern Leaf Blight      diseased          985

In [ ]:
import torch
import sys

print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Python: 3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]
PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4